### DISCUSSION TITLE
Is this Android build time & memory increase expected?

### DISCUSSION THREAD

**Discussion by ghost** [reactwg/react-native-new-architecture#268] [Q&A] [answered]
I am on react-native version "0.76.6" at the moment with the new architecture off. My builds are failing in CircleCI when trying to turn on the new architecture. I did a test build with a larger executor and it passed, but I'm hoping to not have to pay 2x or more for android builds just to be on the new architecture. I'm mainly wondering if this memory jump is expected and caused by react-native itself or possibly some dependency of my app.

### Build memory usage without new arch stays just below 8GB and takes 12-14 mins
<img width="1311" alt="Screenshot 2025-02-22 at 3 09 53 PM" src="https://github.com/user-attachments/assets/af53ec40-87ad-4b38-bbd0-f425e255a8e3" />

### Build memory usage with new arch gets above 12GB and taks >20 mins
<img width="1311" alt="Screenshot 2025-02-22 at 3 10 33 PM" src="https://github.com/user-attachments/assets/8e2ad07a-8376-4127-b74b-e253c6f5948d" />

The only difference between these two builds, besides the larger executor in circleci config, is that I changed `newArchEnabled=false` to `newArchEnabled=true` in `gradle.properties`.

We use the react native community circleci orb and their [linux_android executor](https://circleci.com/developer/orbs/orb/react-native-community/react-native#executors-linux_android) as such:
```
    executor:
      name: rn/linux_android
      # See: https://hub.docker.com/r/reactnativecommunity/react-native-android/tags
      build_image_version: v15.0
      gradle_options: '-Xmx4g -Xms2g -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.jvmargs="-Xmx4g -Xms2g -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"'
      resource_class: large
```

I'll be happy to try to share any additional information that I can. I'm hopeful that others have run into this and solved or, or just know what I can look into to try to mitigate this memory increase if its possible to do so. Thanks in advance for any help.

**Comment by ghost** [comment]
[android_build_output.txt](https://github.com/user-attachments/files/18925364/android_build_output.txt)

The failed build output is here, and it ends with:
```
...
[21:17:59]: ▸ > Task :react-native-share:processReleaseJavaRes NO-SOURCE
[21:17:59]: ▸ > Task :react-native-svg:processReleaseJavaRes NO-SOURCE
[21:17:59]: ▸ > Task :react-native-ui-lib:processReleaseJavaRes NO-SOURCE
[21:17:59]: ▸ > Task :react-native-webview:processReleaseJavaRes
[21:17:59]: ▸ > Task :rn-pendo-sdk:processReleaseJavaRes NO-SOURCE
[21:17:59]: ▸ > Task :segment_analytics-react-native:processReleaseJavaRes
[21:17:59]: ▸ > Task :segment_sovran-react-native:processReleaseJavaRes
[21:17:59]: ▸ > Task :splitsoftware_splitio-react-native:processReleaseJavaRes
[21:18:00]: ▸ > Task :app:mergeProductionReleaseGlobalSynthetics
[21:18:01]: ▸ > Task :app:mergeProductionReleaseJavaResource
[21:18:02]: ▸ > Task :react-native-reanimated:configureCMakeRelWithDebInfo[arm64-v8a]
[21:18:03]: ▸ > Task :react-native-reanimated:configureCMakeRelWithDebInfo[armeabi-v7a]
[21:18:04]: ▸ > Task :react-native-reanimated:configureCMakeRelWithDebInfo[x86]
[21:18:04]: ▸ > Task :react-native-reanimated:configureCMakeRelWithDebInfo[x86_64]
[21:18:04]: ▸ > Task :react-native-reanimated:generateJsonModelRelease
[21:18:04]: ▸ > Task :react-native-reanimated:prefabReleaseConfigurePackage
[21:18:05]: ▸ > Task :app:configureCMakeRelWithDebInfo[arm64-v8a]
[21:18:23]: ▸ > Task :react-native-reanimated:buildCMakeRelWithDebInfo[arm64-v8a]
[21:18:40]: ▸ > Task :app:mergeDexProductionRelease
[21:18:43]: ▸ > Task :react-native-reanimated:buildCMakeRelWithDebInfo[armeabi-v7a]
[21:18:59]: ▸ > Task :react-native-reanimated:buildCMakeRelWithDebInfo[x86]
[21:19:16]: ▸ > Task :react-native-reanimated:buildCMakeRelWithDebInfo[x86_64]
[21:19:17]: ▸ > Task :react-native-reanimated:externalNativeBuildRelease
[21:19:17]: ▸ > Task :react-native-reanimated:prefabReleasePackage
[21:19:47]: ▸ > Task :app:buildCMakeRelWithDebInfo[arm64-v8a]

Too long with no output (exceeded 10m0s): context deadline exceeded
```

Coul it be `react-native-reanimated` that is the issue?

**Comment by cortinico** [comment, marked as answer]
> I'll be happy to try to share any additional information that I can. I'm hopeful that others have run into this and solved or, or just know what I can look into to try to mitigate this memory increase if its possible to do so.

Without seeing your project is hard to say if there is anything that is causing this in particular.

What I can say is that with `newArchEnabled=true`, you'll be also compiling C++ code. That's due to the New Architecture of React Native being in C++, so there is one compiler more to invoke so builds we be (sadly) a bit slower than old arch.

We invested significant amount of time on build optimizations though, so you should probably look into setting up some caching for your CI. If you're rebuilding everything from scratch everytime, the time is going to add up. But if you cache the build output, normally an app rebuild should take a couple of minutes. That's particularly true if you have 3rd party deps such as `reanimated` which also have a lot of C++ code for their New Architecture implementation

**Reply by ghost** [reply]
Thank you for the reply. I'll share some additional things about how the app is built in CI and list the major dependencies of the app as well below. If there is anything else that would be helpful for me to share I'd be happy to do so.

The first thing that might be related to the caching you mention is that when we build in CI (using fastlane) we run these commands every time:
```ruby
lane :build_upload_production do
    gradle(task: "clean")
    gradle(
        task: 'bundle',
        flavor: 'Production',
        build_type: 'Release',
    )
    ...
end
```
Should I consider removing the clean step?


Our entire android build step in Circle CI looks something like this:
```yml
  fastlane_android:
    working_directory: ~/repo
    executor:
      name: rn/linux_android
      # See: https://hub.docker.com/r/reactnativecommunity/react-native-android/tags
      build_image_version: v15.0
      gradle_options: '-Xmx4g -Xms2g -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.jvmargs="-Xmx4g -Xms2g -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"'
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - node/install-packages:
          include-branch-in-cache-key: false
          pkg-manager: yarn
          cache-version: v4
      - ruby/install-deps:
          app-dir: android
          key: gems-v1
          include-branch-in-cache-key: false
      - run:
          command: cd android && bundle exec fastlane build_upload_production
          name: Running lane build_upload_production
```

Here is a list of dependencies in our package.json:
```json
"dependencies": {
    "@datadog/mobile-react-native": "2.6.2",
    "@datadog/mobile-react-navigation": "2.6.2",
    "@expo/react-native-action-sheet": "4.1.0",
    "@fullstory/react-native": "1.7.2",
    "@hookform/resolvers": "4.1.0",
    "@iterable/react-native-sdk": "1.3.21",
    "@react-native-async-storage/async-storage": "2.1.1",
    "@react-native-community/slider": "4.5.5",
    "@react-native-firebase/analytics": "21.7.1",
    "@react-native-firebase/app": "21.7.1",
    "@react-navigation/bottom-tabs": "7.2.0",
    "@react-navigation/devtools": "7.0.15",
    "@react-navigation/drawer": "7.1.1",
    "@react-navigation/material-top-tabs": "7.1.0",
    "@react-navigation/native": "7.0.14",
    "@react-navigation/native-stack": "7.2.0",
    "@reduxjs/toolkit": "2.5.1",
    "@segment/analytics-react-native": "2.20.3",
    "@segment/analytics-react-native-plugin-amplitude-session": "0.4.0",
    "@segment/analytics-react-native-plugin-firebase": "0.4.3",
    "@segment/sovran-react-native": "1.1.3",
    "@splitsoftware/splitio-react-native": "1.1.0",
    "@tanstack/react-query": "5.66.8",
    "color": "4.2.3",
    "lodash": "4.17.21",
    "luxon": "3.5.0",
    "query-string": "7.1.3",
    "react": "18.3.1",
    "react-hook-form": "7.54.2",
    "react-native": "0.76.6",
    "react-native-bootsplash": "6.3.3",
    "react-native-calendars": "1.1309.1",
    "react-native-config": "1.5.5",
    "react-native-date-picker": "5.0.10",
    "react-native-device-info": "14.0.4",
    "react-native-document-picker": "9.3.1",
    "react-native-element-dropdown": "2.12.4",
    "react-native-email-link": "1.16.1",
    "react-native-fs": "2.20.0",
    "react-native-gesture-handler": "2.24.0",
    "react-native-get-random-values": "1.11.0",
    "react-native-image-picker": "8.1.0",
    "react-native-in-app-review": "4.3.3",
    "react-native-keyboard-aware-scroll-view": "0.9.5",
    "react-native-linear-gradient": "2.8.3",
    "react-native-map-link": "3.7.0",
    "react-native-mask-input": "1.2.3",
    "react-native-modal": "13.0.1",
    "react-native-notifications": "5.1.0",
    "react-native-page-indicator": "2.4.1",
    "react-native-pager-view": "6.7.0",
    "react-native-paper": "5.13.1",
    "react-native-permissions": "5.2.5",
    "react-native-reanimated": "3.16.7",
    "react-native-safe-area-context": "5.2.0",
    "react-native-screens": "4.8.0",
    "react-native-share": "12.0.9",
    "react-native-shimmer-placeholder": "2.0.9",
    "react-native-signature-canvas": "4.7.2",
    "react-native-svg": "15.11.1",
    "react-native-tab-view": "4.0.5",
    "react-native-ui-lib": "7.6.2",
    "react-native-uuid": "2.0.3",
    "react-native-webview": "13.13.2",
    "react-redux": "9.2.0",
    "redux-persist": "6.0.0",
    "rn-pendo-sdk": "3.6.0",
    "url-parse": "1.5.10",
    "use-interval": "1.4.0",
    "usehooks-ts": "3.1.1",
    "yup": "1.6.1"
  },
```
